### ISSUE TITLE
Profile picture in title bar.

### ISSUE THREAD

**Issue by positron7120** [lassekongo83/yt-classic-polymer#23]
Can the profile picture in the title bar ![image](https://user-images.githubusercontent.com/81792364/116862207-05bbee80-ac22-11eb-93f1-ab280e0fbd6b.png) be made square?

**Comment by lassekongo83** [comment]
I decided to revert this fix. Tbh, I don't like it, and from the screenshots I've found the avatar was rounded back in 2015. It's not worth adding as an option _(feature bloat)_ as it can be fixed in a UserStyle manager or uBlock Origin for those who want. uBO fix: `youtube.com##ytd-masthead #avatar-btn yt-img-shadow.ytd-topbar-menu-button-renderer:style(border-radius: 0 !important;)`
